/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-6-3 下午7:00' with Gradle 3.2.1
 *
 * @author Administrator, @date 17-6-3 下午7:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
